version: '3.7'

volumes:
  db-volume:

services:
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 6432:5432
    command: ["postgres", "-c", "log_statement=all", "-c", "log_min_duration_statement=1"]
