version: '3.7'

volumes:
  redis-volume:
  db-volume:
  pgadmin-volume:

networks:
  postgres:
    driver: bridge


services:

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    image: redis:alpine
    restart: unless-stopped
    ports:
        - 6379:6379
    volumes:
      - redis-volume:/var/lib/redis/

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 6432:5432
    networks:
      - postgres
    command: ["postgres", "-c", "log_statement=all", "-c", "log_min_duration_statement=1"]
  
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - postgres
    volumes:
        # Don't forget to set owner:group for this dir as 5050:5050
        # (sudo chown -R 5050:5050 <this path>)
        - pgadmin-volume:/var/lib/pgadmin/