[tool.black]
line-length = 120
skip-string-normalization = '1'

[tool.mypy]
python_version = '3.9'
show_error_codes = true
warn_redundant_casts = true
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = false
exclude = [
    'test',
    'conftest',
    'versions',
]


[tool.pydantic-mypy]
warn_untyped_fields = true
